# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x05proto\"$\n\x10InferenceRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"\'\n\x11InferenceResponse\x12\x12\n\nprediction\x18\x01 \x01(\x05\x32I\n\tInference\x12<\n\x07Predict\x12\x17.proto.InferenceRequest\x1a\x18.proto.InferenceResponseB+Z)github.com/ANGEL0CADUTO/IDS_project/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/ANGEL0CADUTO/IDS_project/proto'
  _globals['_INFERENCEREQUEST']._serialized_start=26
  _globals['_INFERENCEREQUEST']._serialized_end=62
  _globals['_INFERENCERESPONSE']._serialized_start=64
  _globals['_INFERENCERESPONSE']._serialized_end=103
  _globals['_INFERENCE']._serialized_start=105
  _globals['_INFERENCE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
