version: '3.8'

services:
  # Servizi applicativi (per ora sono segnaposto)
  collector:
    build:
      context: ./services/collector
    ports:
      - "50051:50051" # Espone la porta gRPC
    networks:
      - ids-net

  analysis:
    build:
      context: ./services/analysis
    networks:
      - ids-net
  
  alerter:
    build:
      context: ./services/alerter
    networks:
      - ids-net
  
  storage:
    build:
      context: ./services/storage
    networks:
      - ids-net

  # Servizi di backend
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=ids-project
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
    networks:
      - ids-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - ids-net

volumes:
  influxdb-data:
  grafana-data:

networks:
  ids-net:
    driver: bridge